---
name: Build ISO installer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-iso:
    name: Build ISO to install system from
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: sleepy-schaf
            base_image: quay.io/fedora-ostree-desktops/silverblue:43
            config: "./iso-silverblue.toml"
            disk-types: "anaconda-iso"
          - image_name: tipsy-tippete
            base_image: quay.io/fedora-ostree-desktops/kinoite:43
            config: "./iso-kinoite.toml"
            disk-types: "anaconda-iso"
          - image_name: majestic-momo
            base_image: quay.io/fedora-ostree-desktops/base-atomic:43
            config: "./iso-dms.toml"
            disk-types: "anaconda-iso"

    steps:
      - name: Prepare environment
        run: |
          USER_UID=$(id -u)
          USER_GID=$(id -g)
          echo "USER_UID=${USER_UID}" >> ${GITHUB_ENV}
          echo "USER_GID=${USER_GID}" >> ${GITHUB_ENV}

      - name: Fetch current date
        shell: bash
        run: |
          TIMESTAMP="$(date +%d-%m-%Y)"
          echo "TIMESTAMP=${TIMESTAMP}" >> ${GITHUB_ENV}

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v9
        with:
          remove-codeql: true

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build ISO
        id: build
        uses: osbuild/bootc-image-builder-action@main
        with:
          builder-image: "quay.io/centos-bootc/bootc-image-builder:latest"
          config-file: ${{ matrix.config }}
          image: ${{ matrix.base_image }}
          chown: ${{ env.USER_UID }}:${{ env.USER_GID }}
          types: ${{ matrix.disk-types }}
          rootfs: ext4
          additional-args: --use-librepo=True

      - name: Upload disk images and Checksum to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image_name }}_${{ env.TIMESTAMP }}
          path: ${{ steps.build.outputs.output-directory }}
          if-no-files-found: error
          retention-days: 90
          compression-level: 0
          overwrite: true
